import AppKit
import BeLauncherCore

/// Polls the pasteboard's change counter. No permission is required, and the watcher
/// deliberately ignores content that is not the user's own text:
/// concealed items (password managers), transient items, and non-text flavours.
@MainActor
final class ClipboardWatcher {
    private let store: Store
    private var timer: Timer?
    private var lastChangeCount: Int
    private(set) var isRunning = false

    init(store: Store) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.7, repeats: true) { _ in
            MainActor.assumeIsolated { [weak self] in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    /// Marks the next pasteboard change as BeLauncher's own so copying a snippet
    /// does not immediately re-enter the history.
    func ignoreNextChange() {
        lastChangeCount = NSPasteboard.general.changeCount + 1
    }

    /// Images live beside the database, in a folder the user can open and delete.
    private func saveImage(_ image: NSImage, source: String) -> String? {
        guard let tiff = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff),
              let png = bitmap.representation(using: .png, properties: [:]) else { return nil }
        let folder = (store.path as NSString).deletingLastPathComponent + "/clipboard-images"
        try? FileManager.default.createDirectory(atPath: folder, withIntermediateDirectories: true)
        let name = SafeFilename.make("clip-\(Int(Date.now.timeIntervalSince1970))", extension: "png")
        let path = folder + "/" + name
        guard (try? png.write(to: URL(fileURLWithPath: path))) != nil else { return nil }
        return path
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        guard !types.contains(concealed), !types.contains(transient), !types.contains(autoGenerated) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName ?? ""

        // Files first: a copied file also carries a string, and the path is the useful part.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty {
            for url in urls.prefix(5) where url.isFileURL {
                store.recordClip(text: url.path, sourceApp: source, kind: .file)
                Sounds.play(.taken)
                // How this person names files, learned from the names they use.
                store.observe(OperatingModel.observeFilename(url.lastPathComponent))
            }
            return
        }

        if let text = pasteboard.string(forType: .string) {
            store.recordClip(text: text, sourceApp: source)
            // The confirmation you asked for, wherever you copied from. And when it does *not*
            // sound, that is information too: a password or an API key was refused before it
            // touched the disk. Silence means "not stored".
            Sounds.play(.taken)
            // Text this person wrote or approved says how they write. Only the conclusion is
            // kept — "escribe corto" — never the paragraph it came from.
            store.observe(OperatingModel.observeWriting(text))
            return
        }

        // An image with no text alongside it: keep a copy so the history can offer it back.
        if let image = NSImage(pasteboard: pasteboard) {
            store.recordClip(text: saveImage(image, source: source) ?? "Imagen copiada",
                             sourceApp: source, kind: .image,
                             assetPath: saveImage(image, source: source) ?? "")
            Sounds.play(.taken)
        }
    }
}
