import AppKit
import BeLauncherCore

/// Polls the pasteboard's change counter. No permission is required, and the watcher
/// deliberately ignores content that is not the user's own text:
/// concealed items (password managers), transient items, and non-text flavours.
@MainActor
final class ClipboardWatcher {
    private let store: Store
    private var timer: Timer?
    private var lastChangeCount: Int
    private(set) var isRunning = false

    init(store: Store) {
        self.store = store
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.7, repeats: true) { _ in
            MainActor.assumeIsolated { [weak self] in self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    /// Marks the next pasteboard change as BeLauncher's own so copying a snippet
    /// does not immediately re-enter the history.
    func ignoreNextChange() {
        lastChangeCount = NSPasteboard.general.changeCount + 1
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        guard !types.contains(concealed), !types.contains(transient), !types.contains(autoGenerated) else { return }

        guard let text = pasteboard.string(forType: .string) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.localizedName ?? ""
        store.recordClip(text: text, sourceApp: source)
    }
}
