import Foundation

// The interface chrome: window titles, menus, buttons, column headers, counters.
//
// These arrived late and all at once. Everything here used to be a Spanish literal written straight
// into a `Text(…)` or a `Button(…)`, which worked as long as the product only had one language and
// stopped working the day it had two: a Mac set to English drew an English window with "13
// resultados" in the footer and "Ajustes" on the button. The interface language is a setting now,
// so nothing the app says to the user may be written at the call site in one language only.

extension SpanishStrings {

    static let interface: [String: String] = [
        "30 days": "30 días",
        "7 days": "7 días",
        "A “no” is remembered for good: I will not ask again.": "Un «no» se recuerda para siempre: no vuelvo a preguntarlo.",
        "ALSO CALLED": "TAMBIÉN SE LLAMA",
        "Actions": "Acciones",
        "CONNECTED WITH": "CONECTADO CON",
        "Clear": "Borrar",
        "Connected: %@": "Conectado: %@",
        "Plan a task": "Planear una tarea",
        "Quick Preview": "Vista previa rápida",
        "Quick actions": "Acciones rápidas",
        "Snippets": "Snippets",
        "Use a saved snippet": "Usar un snippet guardado",
        "Use a macOS Shortcut": "Usar un atajo de macOS",
        "Ask your Brain about %@": "Preguntar al Brain sobre %@",
        "Search your local knowledge and show the sources": "Buscar en tu conocimiento local y mostrar las fuentes",
        "Asking your Brain…": "Preguntando a tu Brain…",
        "Your Brain": "Tu Brain",
        "For the selected item": "Para el elemento seleccionado",
        "Nothing selected": "Nada seleccionado",
        "Type to filter these actions": "Escribe para filtrar estas acciones",
        "Write or paste text to continue": "Escribe o pega el texto para continuar",
        "Write or paste text": "Escribe o pega el texto",
        "Paste or type the text you want to work on…": "Pega o escribe el texto que quieres trabajar…",
        "Paste": "Pegar",
        "Describe what you want done, in your own words.": "Describe con tus palabras qué quieres hacer.",
        "For example: get me working, close the day, or tidy Downloads.": "Por ejemplo: iniciar concentración, cerrar el día u ordenar Descargas.",
        "You will review the plan before anything changes.": "Revisarás el plan antes de que cambie nada.",
        "Show plan": "Ver plan",
        "I do not know how to do that yet. Try one of the examples below.": "Todavía no sé hacer eso. Prueba uno de los ejemplos de abajo.",
        "Remembered": "Recordado",
        "Connections": "Conexiones",
        "Brain updates": "Actualizaciones del Brain",
        "Inbox": "Bandeja de entrada",
        "Review captured notes and voice notes before they become memory.": "Revisa las notas capturadas y de voz antes de convertirlas en memoria.",
        "Inbox is clear": "La bandeja está vacía",
        "Keep in Brain": "Guardar en el Brain",
        "Clipboard waiting": "Portapapeles pendiente",
        "Remove from Inbox": "Quitar del Inbox",
        "Open original source": "Abrir fuente original",
        "Where your Brain looks": "Dónde busca tu Brain",
        "Worth your attention": "Merece tu atención",
        "Recent notes": "Notas recientes",
        "Recent work": "Trabajo reciente",
        "Your private memory for finding, understanding and doing.": "Tu memoria privada para encontrar, entender y hacer.",
        "Private on this Mac": "Privado en este Mac",
        "%@ things · %@ connections": "%@ cosas · %@ conexiones",
        "Confirmation required": "Hace falta confirmación",
        "Run": "Ejecutar",
        "Run shortcut": "Ejecutar atajo",
        "Record Voice Note": "Grabar nota de voz",
        "Dictate Into Current App": "Dictar en la app actual",
        "Read Screen": "Leer pantalla",
        "Write Quick Note": "Escribir nota rápida",
        "Record Call": "Grabar llamada",
        "Search Brain": "Buscar en Brain",
        "Upcoming Meetings": "Próximas reuniones",
        "Start Focus": "Iniciar concentración",
        "Prepare Meeting": "Preparar reunión",
        "Open Notes": "Abrir notas",
        "Open Brain Graph": "Abrir grafo del Brain",
        "Review Voice Notes": "Revisar notas de voz",
        "Run shortcut %@?": "¿Ejecutar el atajo %@?",
        "The shortcut action is unavailable.": "La acción de atajo no está disponible.",
        "The shortcut could not be run": "No se pudo ejecutar el atajo",
        "This shortcut can change settings or control other apps.": "Este atajo puede cambiar ajustes o controlar otras aplicaciones.",
        "Move %@ to the trash?": "¿Mover %@ a la papelera?",
        "Could not write the brain file: %@": "No se pudo escribir el archivo del cerebro: %@",
        "EVIDENCE": "EVIDENCIA",
        "Everything": "Todo",
        "Forget": "Olvidar",
        "Looking through your apps…": "Buscando tus aplicaciones…",
        "Mark important": "Marcar importante",
        "Name match": "Coincidencia por nombre",
        "Nothing here yet. As soon as the brain captures a stretch of work, it shows up.": "Todavía no hay corpus. En cuanto el cerebro capture un rato de trabajo, aparece aquí.",
        "Open": "Abrir",
        "Open file": "Abrir archivo",
        "Choose file": "Elegir archivo",
        "Open brain file": "Abrir archivo del cerebro",
        "Open source": "Abrir origen",
        "The file action could not be completed": "No se pudo completar la acción sobre el archivo",
        "This action cannot be undone.": "Esta acción no se puede deshacer.",
        "Pick something from the list": "Elige algo de la lista",
        "READING": "LEYENDO",
        "RECENT": "RECIENTES",
        "Read here": "Leer aquí",
        "Local action": "Acción local",
        "Needs permission if it is not granted": "Necesita permiso si aún no lo has concedido",
        "Action completed": "Acción completada",
        "The action is unavailable": "La acción no está disponible",
        "The action could not be prepared": "No se pudo preparar la acción",
        "The action could not be completed": "No se pudo completar la acción",
        "Read screen": "Leer pantalla",
        "Read screen with OCR": "Leer pantalla con OCR",
        "Read PDF": "Leer PDF",
        "Upcoming meetings": "Próximas reuniones",
        "Voice notes and dictation": "Notas de voz y dictado",
        "Voice and calls": "Voz y llamadas",
        "Voice notes, dictation and calls": "Notas de voz, dictado y llamadas",
        "Record from any app with ⌥⌘V. Qwen runs in a separate local process; the launcher stays instant.": "Graba desde cualquier app con ⌥⌘V. Qwen corre en un proceso local separado; el launcher sigue instantáneo.",
        "Microphone": "Micrófono",
        "Ready": "Listo",
        "0.6B · Fast": "0.6B · rápido",
        "1.7B · High quality": "1.7B · alta calidad",
        "Permission needed": "Falta permiso",
        "Allow microphone": "Permitir micrófono",
        "Open microphone settings": "Abrir ajustes del micrófono",
        "Install Python 3": "Instalar Python 3",
        "Qwen ASR needs Python %@. Install a compatible version, then return here.": "Qwen ASR necesita Python %@. Instala una versión compatible y vuelve aquí.",
        "Reinstall model": "Reinstalar modelo",
        "Download Qwen3-ASR": "Descargar Qwen3-ASR",
        "Qwen3-ASR · MLX": "Qwen3-ASR · MLX",
        "Automatic": "Automático",
        "Full system audio": "Audio completo del sistema",
        "Capture source": "Fuente de captura",
        "Recording call in %@": "Grabando llamada en %@",
        "Suggested source: %@": "Fuente sugerida: %@",
        "Possible call in %@ — record": "Posible llamada en %@ — grabar",
        "%@ is open — record call": "%@ está abierta — grabar llamada",
        "Shortcuts": "Atajos",
        "Voice note": "Nota de voz",
        "The same capture engine will handle dictation and call recording. Nothing listens until you start it.": "El mismo motor gestionará el dictado y las llamadas. No escucha nada hasta que lo inicias.",
        "Checking local ASR…": "Comprobando ASR local…",
        "Qwen ASR needs an Apple Silicon Mac.": "Qwen ASR necesita un Mac con Apple Silicon.",
        "Preparing the local voice runtime…": "Preparando el motor de voz local…",
        "Not installed. Apple Speech remains available as a fallback.": "No está instalado. Apple Speech queda disponible como fallback.",
        "Installing the local runtime and downloading model weights…": "Instalando el runtime local y descargando los pesos del modelo…",
        "Ready. Audio stays on this Mac.": "Listo. El audio se queda en este Mac.",
        "Qwen ASR could not be installed: %@": "Qwen ASR no pudo instalarse: %@",
        "This audio format could not be prepared for local transcription.": "Este formato de audio no pudo prepararse para la transcripción local.",
        "The local voice setup stopped before finishing. Retry to resume it; your launcher is unaffected.": "La configuración de voz local se detuvo antes de terminar. Reintenta para continuar; el launcher no se ha afectado.",
        "The local voice setup stopped at %@. Retry to continue.": "La configuración de voz local se detuvo en %@. Reintenta para continuar.",
        "The local voice runtime could not be downloaded. Check the connection and retry.": "No se pudo descargar el motor de voz local. Comprueba la conexión y reintenta.",
        "The local voice setup stopped. Retry to continue.": "La configuración de voz local se detuvo. Reintenta para continuar.",
        "download": "descarga",
        "Screen Recording permission is needed for call audio.": "Hace falta permiso de Grabación de pantalla para capturar el audio de una llamada.",
        "There is no display available for system audio capture.": "No hay ninguna pantalla disponible para capturar el audio del sistema.",
        "Record a voice note or dictate into any app with a global shortcut. Audio stays on this Mac.": "Graba una nota de voz o dicta en cualquier app con un atajo global. El audio se queda en este Mac.",
        "The microphone only while you explicitly record or dictate. There is no background listening.": "El micrófono solo se usa cuando grabas o dictas explícitamente. No hay escucha en segundo plano.",
        "The launcher and Brain work normally. Voice notes and dictation stay off.": "El launcher y el Brain siguen funcionando. Las notas de voz y el dictado quedan apagados.",
        "Record voice note": "Grabar nota de voz",
        "Record": "Grabar",
        "Dictate": "Dictar",
        "Write a quick note": "Escribir una nota rápida",
        "Record a voice note": "Grabar una nota de voz",
        "Dictate into the current app": "Dictar en la app actual",
        "Dictate to current app": "Dictar en la app actual",
        "Dictation needs permission to insert the transcription in the app you were using.": "El dictado necesita permiso para insertar la transcripción en la app que estabas usando.",
        "Dictation was not started because insertion permission is not granted.": "El dictado no empezó porque no se ha concedido el permiso para insertar texto.",
        "Transcription inserted in the active app": "Transcripción insertada en la app activa",
        "The app where dictation started is no longer available.": "La app donde empezó el dictado ya no está disponible.",
        "Voice note saved, but dictation could not be inserted.": "La nota de voz se guardó, pero el dictado no se pudo insertar.",
        "Record call": "Grabar llamada",
        "Stop call recording": "Detener grabación de llamada",
        "Recording call": "Grabando llamada",
        "Transcribing call": "Transcribiendo llamada",
        "Call saved in your Brain": "Llamada guardada en tu Brain",
        "Call recording was not saved.": "La grabación de la llamada no se guardó.",
        "Call recording could not start: %@": "La grabación de la llamada no pudo empezar: %@",
        "Call could not be transcribed: %@": "La llamada no pudo transcribirse: %@",
        "Microphone permission is needed for a call recording.": "Hace falta permiso para el micrófono para grabar una llamada.",
        "The call microphone did not start recording.": "El micrófono de la llamada no empezó a grabar.",
    "Extract actions": "Extraer acciones",
    "Save proposals": "Guardar propuestas",
        "Saved to Brain": "Guardado en el Brain",
        "Dictation": "Dictado",
        "Call recording": "Grabación de llamada",
        "Call audio": "Audio de la llamada",
        "System audio": "Audio del sistema",
        "Call recording needs Screen Recording permission to capture the other participants. Audio is kept as separate local evidence.": "La grabación necesita permiso de Grabación de pantalla para capturar a los demás participantes. El audio se conserva como evidencia local separada.",
        "Audio stays on this Mac.": "El audio se queda en este Mac.",
        "Proposals are not committed automatically.": "Las propuestas no se confirman automáticamente.",
        "Transcript": "Transcripción",
        "Proposals": "Propuestas",
        "Reading the call…": "Leyendo la llamada…",
        "Nothing extracted yet.": "Todavía no se ha extraído nada.",
        "Stop voice note": "Detener nota de voz",
        "Stop": "Detener",
        "Open Brain": "Abrir Brain",
        "Your audio stays on this Mac": "Tu audio se queda en este Mac",
        "Ready to capture": "Listo para capturar",
        "Recording": "Grabando",
        "Transcribing": "Transcribiendo",
        "Recording voice note": "Grabando nota de voz",
        "Transcribing voice note": "Transcribiendo nota de voz",
        "Voice note saved in your Brain": "Nota de voz guardada en tu Brain",
        "Voice note was not saved.": "La nota de voz no se guardó.",
        "Voice note could not start: %@": "La nota de voz no pudo empezar: %@",
        "Voice note could not be transcribed: %@": "La nota de voz no pudo transcribirse: %@",
        "Microphone permission is needed for a voice note.": "Hace falta permiso para usar el micrófono en una nota de voz.",
        "The microphone did not start recording.": "El micrófono no empezó a grabar.",
        "This recording is too short to transcribe (%@ seconds).": "Esta grabación es demasiado corta para transcribirla (%@ segundos).",
        "This recording contains no audible microphone signal (%@ seconds). Check the microphone input and record again.": "Esta grabación no contiene señal audible del micrófono (%@ segundos). Comprueba la entrada del micrófono y vuelve a grabar.",
        "Ready to transcribe · click to continue": "Lista para transcribir · haz clic para continuar",
        "Ready for your review · click to continue": "Lista para revisar · haz clic para continuar",
        "Transcribe now": "Transcribir ahora",
        "Mark as reviewed": "Marcar como revisada",
        "My notes": "Mis notas",
        "Write, edit and keep your Markdown notes in one place.": "Escribe, edita y guarda tus notas Markdown en un solo lugar.",
        "Search notes": "Buscar notas",
        "No notes yet": "Todavía no hay notas",
        "No notes match your search": "Ninguna nota coincide con tu búsqueda",
        "Ready to transcribe": "Lista para transcribir",
        "Reviewed": "Revisada",
        "Needs review": "Pendiente de revisar",
        "Markdown note · %@": "Nota Markdown · %@",
        "reviewed": "revisada",
        "in Inbox": "en Inbox",
        "Open the Markdown file in Finder": "Abrir el archivo Markdown en Finder",
        "Review this note when you are done with it.": "Revisa esta nota cuando hayas terminado con ella.",
        "Select a note to read or edit": "Selecciona una nota para leerla o editarla",
        "Saved": "Guardado",
        "Invalid provider endpoint.": "La dirección del proveedor no es válida.",
        "Provider answered HTTP %@.": "El proveedor respondió HTTP %@.",
        "The local provider is running but returned no models.": "El proveedor local está activo, pero no devolvió modelos.",
        "The download finished, but Ollama has not reported %@ yet. Try checking again.": "La descarga terminó, pero Ollama todavía no reporta %@. Vuelve a comprobarlo.",
        "verify downloaded model": "verificar el modelo descargado",
        "Reading “%@” here.": "Leyendo «%@» aquí.",
        "Save": "Guardar",
        "Saved. From now on this file is yours: the machine will not rewrite it.": "Guardado. A partir de ahora este archivo es tuyo: la máquina no lo reescribe.",
        "Search your memory": "Buscar en tu memoria",
        "Settings": "Ajustes",
        "Show the file in the Finder. It is yours and it is an ordinary .md.": "Enseñar el archivo en el Finder. Es tuyo y es un .md normal.",
        "There is nothing readable for this node yet.": "Este nodo todavía no tiene nada legible.",
        "These were not the same thing: give it its own entry back.": "Esto no era lo mismo: devuélvele su ficha propia.",
        "This node": "Este nodo",
        "This node has no source to open.": "Este nodo no tiene un origen que abrir.",
        "Try again": "Reintentar",
        "Unmark important": "Quitar importancia",
        "WHAT YOU TOUCHED": "QUÉ TOCASTE",
        "What you write here outranks whatever the machine worked out, and never gets overwritten.": "Lo que escribas aquí manda sobre lo que dedujo la máquina y no se sobrescribe.",
        "outside the graph": "fuera del grafo",
        "written by you": "escrito por ti",
        "%@ result": "%@ resultado",
        "%@ results": "%@ resultados",
        "CLIPBOARD": "PORTAPAPELES",
        "Error": "Error",
        "Loading": "Cargando",
        "No results": "Sin resultados",
        "Recent": "Recientes",
        "Try 2+2 · 10 km to mi · f report": "Prueba 2+2 · 10 km to mi · f informe",
        "Could not save: %@": "No se pudo guardar: %@",
        "I see nothing saying “%1$@” and “%2$@” are the same thing.": "No veo nada que diga que «%1$@» y «%2$@» son lo mismo.",
        "It has turned up %@ times in what you do.": "Ha aparecido %@ veces en lo que haces.",
        "Nothing matches “%@”.": "Nada coincide con «%@».",
        "“%1$@” is now an alias of “%2$@”. %3$@.": "«%1$@» ahora es un alias de «%2$@». %3$@.",
        "“%@” has no entry of its own yet.": "«%@» todavía no tiene ficha propia.",
        "Add": "Añadir",
        "Also when the window opens and closes": "También al abrir y cerrar la ventana",
        "App name": "Nombre de la app",
        "Ask your brain": "Pregúntale al cerebro",
        "BeLauncher has no account, no analytics and no server. It only looks for a new version when you ask it to, and installs it itself: no dragging the app over the old one.": "BeLauncher no tiene cuenta, ni analítica, ni servidor. Solo mira si hay versión nueva cuando se lo pides, y la instala él mismo: nada de arrastrar la app encima de la vieja.",
        "Check now": "Buscar ahora",
        "Checking Apple's signature…": "Comprobando la firma de Apple…",
        "Clear the history": "Borrar el historial",
        "Close an app that hung": "Cerrar una app que se colgó",
        "Confidential things never leave the Mac": "Lo confidencial nunca sale del Mac",
        "Copies that password managers mark as confidential are never kept, nor is anything shaped like a credential. This is for whatever else you would rather leave out.": "Nunca se guardan las copias que los gestores de contraseñas marcan como confidenciales, ni nada con forma de credencial. Esto es para lo demás que prefieras dejar fuera.",
        "Deactivate this Mac": "Desactivar en este equipo",
        "Email": "Correo",
        "Find files": "Buscar archivos",
        "Get me ready for a meeting": "Prepárame para una reunión",
        "Give it something to do (type “/”)": "Encárgale algo (escribe «/»)",
        "Go to a path": "Ir a una ruta",
        "It sounds every time you copy anything, in any app: that is the confirmation it was kept. **If it stays quiet, it was not kept** — a password, or something shaped like a key. The silence says something too.": "Suena cada vez que copias algo, en cualquier app: es la confirmación de que quedó guardado. **Si no suena, es que no lo guardó** — una contraseña o algo con forma de clave. El silencio también dice algo.",
        "Jot something down fast": "Apuntar algo rápido",
        "Keep the Mac awake": "Que no se duerma el Mac",
        "Keep what you copy": "Guardar lo que copias",
        "Key": "Clave",
        "Look again": "Volver a buscar",
        "Make a sound when you copy": "Avisar con un sonido al copiar",
        "Models on your Mac": "Modelos en tu Mac",
        "Name": "Nombre",
        "No active licence.": "Sin licencia activa.",
        "No key, no cost per token, and nothing leaves this Mac.": "Sin clave, sin coste por token y sin que nada salga de este Mac.",
        "None yet.": "Ninguno todavía.",
        "None. Whatever you copy from any app gets kept.": "Ninguna. Lo que copies desde cualquier app se guarda.",
        "Off on purpose: copying happens dozens of times a day and opening the window happens hundreds. Try it and decide.": "Viene apagado a propósito: copiar son decenas de veces al día y abrir la ventana son cientos. Pruébalo y decide.",
        "Open ollama.com": "Abrir ollama.com",
        "Open the latest from a project": "Abrir lo último de un proyecto",
        "Paste into the previous app when you pick": "Pegar en la app anterior al elegir",
        "Pick up where you were before the call": "Retomar lo de antes de la llamada",
        "Read what is on screen": "Leer lo que hay en pantalla",
        "Save where every window is": "Guardar dónde está cada ventana",
        "Search Google, Claude, ChatGPT…": "Buscar en Google, Claude, ChatGPT…",
        "See what is eating the Mac": "Ver qué consume el Mac",
        "Seen lately: ": "Vistas últimamente: ",
        "Sound": "Sonido",
        "The keys go into your Keychain and the requests leave your Mac straight for the provider: nothing passes through Believe and you pay whoever you choose. They are never included in an export.": "Las claves van a tu Llavero y las peticiones salen de tu Mac directas al proveedor: nada pasa por Believe y le pagas a quien tú elijas. Nunca se incluyen en una exportación.",
        "The sounds are generated inside the app rather than played from files, which is why they sound like no other Mac you have used.": "Los sonidos se generan dentro de la app, no son archivos: por eso no se parecen a los de ninguna otra.",
        "They appear with ⌘K over any text in the clipboard.": "Aparecen con ⌘K sobre cualquier texto del portapapeles.",
        "This Mac": "Este equipo",
        "Tokens: {clipboard} {date} {time} {uuid} {cursor} {secret:NAME}": "Fichas: {clipboard} {date} {time} {uuid} {cursor} {secret:NOMBRE}",
        "Type an intent": "Escribe una intención",
        "Version": "Versión",
        "What is slipping": "Qué se me escapa",
        "What we decided about something": "Qué decidimos sobre algo",
        "What we promised somebody": "Qué prometimos a alguien",
        "What you can ask it for": "Qué puedes pedirle",
        "Which model answers": "Qué modelo responde",
        "Who somebody is": "Quién es alguien",
        "With this on, pulling tasks out of a meeting or anything marked as company material only goes to a local model. If there is none, it refuses rather than sending it anyway.": "Con esto activado, sacar tareas de una reunión o cualquier cosa marcada como material de empresa solo va a un modelo local. Si no hay ninguno, se niega en vez de enviarlo igualmente.",
        "Your keys": "Tus claves",
        "key": "clave",
        "local only": "solo local",
        "%@ is running": "%@ está corriendo",
        "%@ times · already in use": "%@ veces · ya se aplica",
        "%@ times · still watching": "%@ veces · todavía mirando",
        "Delete after %@ days": "Borrar después de %@ días",
        "Done: %@ is installed.": "Listo: la %@ se instaló.",
        "Keep at most %@": "Guardar como mucho %@",
        "Showing the last 12 of %@.": "Se muestran las 12 últimas de %@.",
        "App language": "Idioma de la app",
        "BeLauncher speaks MCP: the assistant you already pay for can consult your brain without opening the launcher.": "BeLauncher habla MCP: el asistente que ya pagas puede consultar tu cerebro sin abrir el launcher.",
        "Brain status": "Estado del cerebro",
        "Brings your snippets and links across. It never overwrites: if you already have that keyword, yours wins and we tell you how many were skipped.": "Trae tus snippets y enlaces. Nunca sobrescribe: si ya tienes esa palabra clave, la tuya gana y te decimos cuántas se omitieron.",
        "Coming from another launcher": "Venir de otro launcher",
        "Commands travel with the house rules inside them: the tone, the formats and who approves. Without that, sharing a command is sharing nothing but a name. If you already have one by that name, yours wins and you are told how many were skipped.": "Los comandos viajan con las reglas de la casa dentro: el tono, los formatos y quién aprueba. Sin eso, compartir un comando es compartir solo un nombre. Si ya tienes uno con ese nombre, el tuyo gana y se te dice cuántos se omitieron.",
        "Commands with “/”": "Comandos con «/»",
        "Copy the configuration": "Copiar la configuración",
        "Database": "Base de datos",
        "Delete the working memory": "Borrar la memoria de trabajo",
        "Diagnostics…": "Diagnóstico…",
        "Forget all of it": "Olvidarlo todo",
        "From Claude, ChatGPT or Gemini": "Desde Claude, ChatGPT o Gemini",
        "House rules, one per line, in the form “Name: value”. They travel inside every shared command, which is what makes your team's /proposal produce your proposal rather than whatever the model comes up with.": "Reglas de la casa, una por línea, con el formato «Nombre: valor». Viajan dentro de cada comando compartido, que es lo que hace que el /propuesta de tu equipo produzca vuestra propuesta y no la que se le ocurre al modelo.",
        "How you work": "Cómo trabajas",
        "How your brain fills up": "Cómo se llena tu cerebro",
        "Import from Alfred": "Importar de Alfred",
        "Import from Raycast…": "Importar de Raycast…",
        "It gets written into that app's configuration **keeping whatever was already there**. You have to restart it afterwards for it to notice.": "Se escribe en la configuración de esa app **conservando lo que ya tuviera**. Después hay que reiniciarla para que lo vea.",
        "It has not learned anything yet.": "Todavía no ha aprendido nada.",
        "It keeps who, which project, which file and which meeting, and how they connect. It is what makes “what did we promise Andrés?” or “pick up what I was doing before the call” work at all. It keeps **names and dates, never the contents** of a file, a message or a page.": "Guarda quién, qué proyecto, qué archivo y qué reunión, y cómo se conectan. Es lo que hace que funcione «¿qué prometimos a Andrés?» o «retoma lo que estaba haciendo antes de la llamada». Guarda **nombres y fechas, nunca el contenido** de un archivo, un mensaje o una página.",
        "It learns from what you accept and from what you rewrite: whether you cut things short, whether you open with a greeting, how you name your files. Nothing changes what it produces until four observations agree. **The conclusion is kept, never the text** it came from.": "Aprende de lo que aceptas y de lo que reescribes: si acortas, si saludas, cómo nombras los archivos. Nada cambia lo que produce hasta que cuatro observaciones coinciden. **Se guarda la conclusión, nunca el texto** del que salió.",
        "None. You can make one with ⌘K over any app.": "Ninguno. Puedes crear uno con ⌘K sobre cualquier app.",
        "Nothing goes in without you confirming it. A brain that writes itself is a brain you cannot trust.": "Nada entra sin que tú lo confirmes. Un cerebro que se escribe solo es un cerebro en el que no puedes confiar.",
        "Nothing noted.": "Nada anotado.",
        "Only http, https and mailto. BeLauncher never runs scripts.": "Solo http, https y mailto. BeLauncher nunca ejecuta scripts.",
        "Open the folder": "Abrir la carpeta",
        "Read the read-me": "Leer el LÉEME",
        "Rebuild the structure": "Rehacer la estructura",
        "Remember what I have been working on": "Recordar en qué he estado trabajando",
        "Seven folders already made, each with a note saying what goes inside, and a read-me that explains the whole thing. Open it whenever you are unsure where to put something.": "Siete carpetas ya creadas, cada una con una nota que dice qué va dentro, y un LÉEME que lo explica entero. Ábrelo si alguna vez dudas de dónde poner algo.",
        "Seven tools: remember, context for a task, what you were doing, what we decided, get ready, search and propose. Read and propose only: an assistant can suggest what it thinks the company believes, never decide it.": "Siete herramientas: recordar, contexto de una tarea, qué estabas haciendo, qué decidimos, preparar, buscar y proponer. Solo lectura y propuesta: un asistente puede sugerir qué cree la empresa, nunca decidirlo.",
        "Share with the team": "Compartir con el equipo",
        "Show in Finder": "Ver en Finder",
        "Still empty.": "Todavía vacía.",
        "Team": "Equipo",
        "The language of the window. Your brain does not change: it keeps saving and finding what you wrote in the language you wrote it in.": "El idioma de la ventana. Tu cerebro no cambia: sigue guardando y encontrando lo que escribiste en el idioma en que lo escribiste.",
        "Type “/” in the launcher and the list appears. A command is not a shortcut: it looks at the context, asks for the permissions it needs, shows you what it is about to do, and leaves a receipt of what it did.": "Escribe «/» en el lanzador y sale la lista. Un comando no es un atajo: mira el contexto, pide los permisos que necesite, te enseña qué va a hacer y deja recibo de lo que hizo.",
        "URL template": "Plantilla de URL",
        "Use them in snippets or workflows as {secret:NAME}. They are never exported.": "Úsalos en snippets o workflows como {secret:NOMBRE}. Nunca se exportan.",
        "When a job is not one answer but several pieces, a canvas opens: every block fills itself in, you edit it, and you run whichever ones you want. It closes and it is gone: not one more document to keep.": "Cuando un encargo no es una respuesta sino varias piezas, se abre un lienzo: cada bloque se rellena solo, lo editas y ejecutas lo que quieras. Se cierra y desaparece: no es un documento más que mantener.",
        "Where it lives": "Dónde vive",
        "With anything in front of you: an error, an invoice, an email, a table. It first tries to read whatever you have **selected**, which needs no screen permission. Only if there is no selection does it take a picture, read it on your Mac with Apple's recogniser, and throw it away. **No image is ever kept or uploaded.**": "Con cualquier cosa delante: un error, una factura, un correo, una tabla. Primero intenta leer lo que tengas **seleccionado**, que no necesita permiso de pantalla. Solo si no hay selección hace una foto, la lee en tu Mac con el reconocimiento de Apple y la descarta. **Ninguna imagen se guarda ni se sube.**",
        "With clipboard…": "Con portapapeles…",
        "Your data": "Tus datos",
        "get me ready for …": "prepárame para …",
        "remember that …": "recordar que …",
        "what did we decide about …": "qué decidimos sobre …",
        "Only the memories tagged “shared” go out, encrypted with a phrase only your team has. Believe never sees the key or the contents. What arrives, arrives as a proposal: nothing applies itself.": "Solo salen las memorias etiquetadas como “shared”, cifradas con una frase que solo tiene tu equipo. Believe nunca ve la clave ni el contenido. Lo que llega llega como propuesta: nada se aplica solo.",
        "Starting BeLauncher and asking it, exactly as your assistant would…": "Arrancando BeLauncher y preguntándole, igual que haría tu asistente…",
        "The calendar is asked for the first time you get ready for a meeting. Accessibility, the first time you place a window or paste into the previous app. Notifications, the first time a flow sets a timer. Nothing at launch.": "El calendario se pide la primera vez que preparas una reunión. Accesibilidad, la primera vez que colocas una ventana o pegas en la app anterior. Notificaciones, la primera vez que un flujo pone un temporizador. Nada al arrancar.",
        "It notes **what kind of thing** you do and when — opening this app, running that command — never its contents. When the same sequence repeats four times, it offers to turn it into a command. If you say no, it never asks about that one again. It deletes itself after %@ days.": "Anota **qué tipo de cosa** haces y cuándo — abrir tal app, ejecutar tal comando — nunca su contenido. Cuando la misma secuencia se repite cuatro veces, te ofrece convertirla en un comando. Si dices que no, no se vuelve a preguntar por esa. Se borra sola a los %@ días.",
        "pick up what I was doing": "retoma lo que estaba haciendo",
        "Gathers what you know about somebody before you see them.": "Reúne lo que sabes de alguien antes de verle.",
        "It offers to keep something. You confirm.": "Propone guardar algo. Tú confirmas.",
        "What is going stale: contradictions, overdue things, nothing reviewed.": "Qué se está pudriendo: contradicciones, vencidos, sin revisar.",
        "What still stands today, not everything that was said.": "Lo que está vigente hoy, no todo lo que se dijo.",
        "With your notes on the clipboard, it pulls out decisions and commitments.": "Con tus notas copiadas, saca decisiones y compromisos.",
        "get me ready for Acme": "prepárame para Acme",
        "note call Andrés": "nota llamar a Andrés",
        "open the latest from Atlas": "abre lo último de Atlas",
        "save workspace": "guardar espacio trabajo",
        "what did we decide about pricing": "qué decidimos sobre pricing",
        "what did we promise Andrés": "qué prometimos a Andrés",
        "who is Acme": "quién es Acme",
        "AND WHAT IT DOES NOT": "Y QUÉ NO",
        "BeLauncher settings": "Ajustes de BeLauncher",
        "Delete the last hour, the afternoon or the whole day, and it tells you what goes before it does it.": "Borra la última hora, la tarde o el día entero, y te dice qué se lleva antes de hacerlo.",
        "Done": "Listo",
        "Edit": "Edición",
        "It could not be closed": "No se pudo cerrar",
        "It could not be forced to quit": "No se pudo forzar la salida",
        "It could not be moved to the trash": "No se pudo mover a la papelera",
        "It could not be saved": "No se pudo guardar",
        "Look for apps again": "Volver a buscar aplicaciones",
        "No thanks": "No, gracias",
        "Not now": "Ahora no",
        "Nothing": "Nada",
        "Nothing goes out to the internet unless you set up a model of your own outside it.": "Nada sale a internet salvo que tú configures un modelo de fuera.",
        "Open BeLauncher": "Abrir BeLauncher",
        "Open With failed": "No se pudo guardar",
        "Password managers, the keychain and banks. You can add more.": "Gestores de contraseñas, el llavero y los bancos. Puedes añadir más.",
        "Paste without formatting": "Pegar sin formato",
        "Quick guide": "Guía rápida",
        "Select all": "Seleccionar todo",
        "Select what you want first": "Selecciona primero lo que quieres",
        "Settings…": "Ajustes…",
        "Shall I turn it into a command?": "¿Lo convierto en un comando?",
        "Shall it remember what you work on?": "¿Dejas que recuerde en qué trabajas?",
        "Size": "Tamaño",
        "The command could not be made": "No se pudo crear el comando",
        "The titles of the pages you read, from Safari and Chrome.": "Títulos de las páginas que leíste, de Safari y Chrome.",
        "Turn the memory on": "Activar la memoria",
        "WHAT IT WATCHES": "QUÉ MIRA",
        "What you asked in your own sessions, which are already in your folder.": "Lo que preguntaste en tus sesiones, que ya están en tu carpeta.",
        "What you opened and how long you stayed. The name, never the contents.": "Qué abriste y cuánto rato estuviste. El nombre, nunca el contenido.",
        "Who you met and what you copied while you worked.": "Con quién te viste y lo que copiaste mientras trabajabas.",
        "Yes, make it": "Sí, créalo",
        "You can change any of this in Settings whenever you like.": "Puedes cambiar todo esto en Ajustes cuando quieras.",
        "Your brain…": "Tu cerebro…",
        "Your corpus": "Tu corpus",
        "· turn off": " · desactivar",
        "%1$@ windows across %2$@ display(s). Type “%3$@” to place them.": "%1$@ ventanas en %2$@ pantalla(s). Escribe «%3$@» para colocarlas.",
        "%1$@, from %2$@": "%1$@, de %2$@",
        "%@ apps are excluded from day one.": "Hay %@ apps excluidas desde el primer día.",
        "And you can make it forget.": "Y puedes hacer que olvide.",
        "One click stops the capture, and nothing is recorded until you start it again.": "Un clic detiene la captura, y no se registra nada hasta que la vuelves a arrancar.",
        "Pause whenever you want.": "Pausa cuando quieras.",
        "Saved “%@”": "Guardado «%@»",
        "Seen in %@": "Visto en %@",
        "There is a new version: %@": "Hay una versión nueva: %@",
        "\n\nIt gets kept as a flow called “%@”, which you can edit or delete whenever you want.": "\n\nSe guardará como un flujo llamado «%@», que puedes editar o borrar cuando quieras.",
        "Captured from BeLauncher": "Capturado desde BeLauncher",
        "I cannot find it": "No lo encuentro",
        "It could not be confirmed": "No se pudo confirmar",
        "Kept in the brain": "Guardado en el cerebro",
        "Look for it and confirm it whenever you want.": "Búscala y confírmala cuando quieras.",
        "Mark the text, the table or the error you want me to deal with and press ⌥⇧Space again. It used to read the whole screen and offer things about whatever happened to be in front of you, which was noise more often than help.": "Marca el texto, la tabla o el error del que quieres que me ocupe y vuelve a pulsar ⌥⇧Espacio. Antes leía la pantalla entera y ofrecía cosas al azar, que era peor que no ofrecer nada.",
        "Mission finished": "Misión terminada",
        "Open with": "Abrir con",
        "Remember this": "Recordar esto",
        "That command is not installed any more.": "Ese comando ya no está instalado.",
        "The alias could not be saved": "No se pudo guardar el alias",
        "The command could not be run": "No se pudo ejecutar el comando",
        "The window could not be placed": "No se pudo colocar la ventana",
        "Without this, BeLauncher only finds what you file by hand. With it, you can ask **how you solved something two months ago** and get an answer.": "Sin esto, BeLauncher solo encuentra lo que guardas a mano. Con esto, puedes preguntarle **cómo resolviste algo hace dos meses** y te contesta.",
        "Write the phrase you will remember it by. It is kept as a proposal until you confirm it.": "Escribe la frase con la que lo recordarás. Se guardará como propuesta hasta que la confirmes.",
        "Write the short text you want to find it by. One word, no spaces.": "Escribe el texto corto con el que quieres encontrarlo. Una sola palabra, sin espacios.",
        "%@?": "¿%@?",
        "Alias for %@": "Alias para %@",
        "Careful: it would clash with %@ memory/memories still standing.": "Ojo: chocaría con %@ memoria(s) vigente(s).",
        "Could not open %@": "No se pudo abrir %@",
        "Open %@": "Abrir %@",
        "Placing “%@”": "Colocando «%@»",
        "Action history cleared.": "Historial de acciones borrado.",
        "Configuration copied. Paste it into the Claude Desktop file.": "Configuración copiada. Pégala en el archivo de Claude Desktop.",
        "Encrypted with the team phrase.": "Cifrado con la frase del equipo.",
        "Everything it learned about how you work has been forgotten.": "Olvidado todo lo aprendido sobre cómo trabajas.",
        "I found no Alfred snippets on this Mac.": "No encontré snippets de Alfred en este Mac.",
        "Index rebuilt. With no model, it searches for exact words.": "Índice rehecho. Sin modelo, se busca por palabras exactas.",
        "Mac released.": "Equipo liberado.",
        "No update feed is configured.": "No hay feed de actualizaciones configurado.",
        "Pick the file you exported from Raycast.": "Elige el archivo que exportaste desde Raycast.",
        "Pick the team's encrypted package.": "Elige el paquete cifrado del equipo.",
        "Reply with one word only: ready": "Responde solo con la palabra: listo",
        "Share your commands with the team.": "Comparte tus comandos con el equipo.",
        "Skipped because you already have one by that name:": "Omitidos porque ya tienes uno con ese nombre: ",
        "Team phrase": "Frase del equipo",
        "That was the last one on the list, so the factory ones come back. To exclude no app at all, leave one you never use.": "Era la última de la lista, así que vuelven las de fábrica. Para no excluir ninguna app, deja solo una que no uses.",
        "The model stopped answering halfway. What was indexed stays: press again and it carries on from where it was.": "El modelo dejó de responder a mitad. Lo indexado se queda guardado: vuelve a pulsar y sigue desde donde iba.",
        "The phrase this package was encrypted with.": "La frase con la que se cifró este paquete.",
        "The same one the rest of the team uses. We neither keep it nor see it: if it is lost, the package cannot be opened.": "La misma que use el resto del equipo. No la guardamos ni la vemos: si se pierde, el paquete no se puede abrir.",
        "The structure was already complete.": "La estructura ya estaba completa.",
        "There is nothing to share yet: no memories marked “shared”, no commands, no flows of your own.": "No hay nada que compartir todavía: ni memorias marcadas como “shared”, ni comandos, ni flujos propios.",
        "We could not deactivate right now. Try again in a moment.": "No pudimos desactivar ahora. Intenta de nuevo en un momento.",
        "Working memory cleared.": "Memoria de trabajo borrada.",
        "%1$@ installed. %2$@ skipped because you already have a command by that name.": "Instalados %1$@. Omitidos %2$@ porque ya tienes un comando con ese nombre.",
        "%@ command(s) installed.": "Instalados %@ comando(s).",
        "%@ key deleted.": "Clave de %@ borrada.",
        "%@ key saved to the Keychain.": "Clave de %@ guardada en el Llavero.",
        "%@ memories from the team are waiting for you to confirm them. Nothing applied itself.": "%@ memorias del equipo esperan tu confirmación. Nada se aplicó solo.",
        "Exported %1$@ memories, %2$@ command(s) and %3$@ flow(s), all encrypted.": "Exportadas %1$@ memorias, %2$@ comando(s) y %3$@ flujo(s), todo cifrado.",
        "From the team · %@": "Del equipo · %@",
        "From the team · contradicts “%@”": "Del equipo · contradice «%@»",
        "It could not be exported: %@": "No se pudo exportar: %@",
        "Raycast: %1$@ snippets and %2$@ links": "Raycast: %1$@ snippets y %2$@ enlaces",
        "The Keychain refused the key: %@": "El Llavero rechazó la clave: %@",
        "The structure could not be made: %@": "No se pudo crear la estructura: %@",
        "They could not be exported: %@": "No se pudieron exportar: %@",
        "We could not check for updates: %@": "No pudimos consultar las actualizaciones: %@",
        "You are on the latest version (%@).": "Estás en la última versión (%@).",
        "team: %@": "equipo: %@",
        "A permission is missing": "Falta un permiso",
        "Audience, offer, concept, landing page, ads, email and tasks.": "Audiencia, oferta, concepto, landing, anuncios, email y tareas.",
        "Failed": "Falló",
        "First meeting": "Primera reunión",
        "From raw notes it pulls out decisions and commitments, and offers them to you one at a time for the brain.": "De las notas en crudo saca decisiones y compromisos, y te los propone uno a uno para el cerebro.",
        "I could not think of anything to do with that. Better to say so than to make something up.": "No se me ocurrió nada que hacer con eso. Mejor decirlo que inventarlo.",
        "It gathers who is coming, what was decided last time and what is still open, and leaves you a script before you walk in.": "Reúne quién viene, qué se decidió la última vez y qué está pendiente, y te deja un guion antes de entrar.",
        "It goes back over what you did, pulls out what was left open, and keeps it in your brain.": "Repasa lo que hiciste, saca lo que quedó pendiente y lo guarda en tu cerebro.",
        "It writes the follow-up in the right tone, knowing where things were left.": "Escribe el seguimiento con el tono correcto y sabiendo dónde quedó la cosa.",
        "Looking at the context": "Mirando el contexto",
        "Open settings": "Abrir ajustes",
        "Price and timings": "Precio y plazos",
        "Profile, access, deliverables, folder and a kick-off agenda, in one pass.": "Ficha, accesos, entregables, carpeta y agenda de arranque, en una pasada.",
        "Solution": "Solución",
        "The file is not a BeLauncher package.": "El archivo no es un paquete de BeLauncher.",
        "Waiting for your go-ahead": "Esperando tu visto bueno",
        "What did not": "Qué no",
        "What happened": "Qué pasó",
        "What worked": "Qué funcionó",
        "Where we left it": "Dónde lo dejamos",
        "Who they are": "Quién es",
        "Working out the plan": "Preparando el plan",
        "_(empty)_": "_(vacío)_",
        "actions": "acciones",
        "nothing": "nada",
        "what is on screen": "lo que hay en pantalla",
        "what you copied": "lo que copiaste",
        "what you have selected": "lo que tienes seleccionado",
        "your brain": "tu cerebro",
        "your calendar": "tu calendario",
        "your files": "tus archivos",
        "your work history": "tu historial de trabajo",
        "A %@ min timer": "Temporizador de %@ min",
        "Ask the AI: %@": "Pedir a la IA: %@",
        "Close process %@": "Cerrar el proceso %@",
        "Commission “%@”": "Encargar «%@»",
        "Force process %@ to quit": "Forzar la salida del proceso %@",
        "Get %@ back out of the trash": "Recuperar %@ de la papelera",
        "Give %@ an alias": "Asignar un alias a %@",
        "Keep a note: %@": "Guardar una nota: %@",
        "Move %@ to the trash": "Mover a la papelera %@",
        "Move file to the trash": "Mover archivo a la papelera",
        "Show file": "Mostrar archivo",
        "Open a canvas: %@": "Abrir un lienzo: %@",
        "Place the layout “%@”": "Colocar el reparto «%@»",
        "Place the window: %@": "Colocar la ventana: %@",
        "Run a flow of %@ steps": "Ejecutar un flujo de %@ pasos",
        "Run the mission “%@”": "Ejecutar la misión «%@»",
        "Run the shortcut “%@”": "Ejecutar el atajo «%@»",
        "Save the window layout “%@”": "Guardar el reparto de ventanas «%@»",
        "System command: %@": "Comando del sistema: %@",
        "Apple does not recognise the download as notarised. Nothing was installed.": "Apple no reconoce la descarga como notarizada. No se instaló nada.",
        "By CPU": "Por CPU",
        "By memory": "Por memoria",
        "Conversation": "Conversación",
        "Decision": "Decisión",
        "It has not turned up in anything you have done here yet.": "Todavía no ha aparecido en nada de lo que has hecho aquí.",
        "It needs you to decide": "Necesita que decidas",
        "Meeting": "Reunión",
        "No connections yet.": "Sin conexiones todavía.",
        "Nothing was installed.": "No se instaló nada.",
        "Nothing: it was done with a local model.": "Nada: se hizo con un modelo local.",
        "The download could not be opened. It may have been cut off halfway; try again.": "No se pudo abrir la descarga. Puede que se cortara a medias; reintenta.",
        "The download does not contain a BeLauncher app. Nothing was installed.": "La descarga no contiene una app de BeLauncher. No se instaló nada.",
        "The model returned nothing.": "El modelo no devolvió nada.",
        "%@ returned no text.": "%@ no devolvió texto.",
        "There is no recent meeting to go back to": "No hay ninguna reunión reciente que retomar",
        "WindowServer draws everything you see. Closing it throws you out of the session instantly and you lose whatever you had not saved.": "WindowServer dibuja todo lo que ves. Cerrarlo te saca de la sesión al instante y pierdes lo que no hayas guardado. Suele estar arriba porque el Mac está ocupado, no porque esté colgado.",
        "With nothing in the calendar, there is no “before” to talk about.": "Sin nada en el calendario, no hay un «antes» del que hablar.",
        "You kept it yourself.": "Lo guardaste tú.",
        "You went past it once for a few seconds, so it did not make it into the search.": "Pasaste por ahí una vez y unos segundos, así que no entró en el buscador.",
        "\n## Also called\n\n": "\n## También se llama\n\n",
        "\n## Turns up with\n\n": "\n## Aparece con\n\n",
        "\n## What it has to do with\n\n": "\n## Con qué tiene que ver\n\n",
        "\n## What you touched\n\n": "\n## Qué tocaste\n\n",
        "\n## Where it comes from\n\n": "\n## De dónde sale\n\n",
        "came out of": "salió de",
        "git init failed. Do you have Xcode's command line tools?": "git init falló. ¿Tienes las herramientas de línea de comandos de Xcode?",
        "invalid endpoint": "endpoint inválido",
        "is part of": "forma parte de",
        "kernel_task is macOS itself. It cannot be closed, and when it climbs it is usually the system managing heat: it will come down on its own.": "kernel_task es el propio macOS. No se puede cerrar, y cuando sube suele ser el sistema gestionando el calor: se baja solo.",
        "macOS is running the app from a read-only copy. Move it to Applications and open it from there.": "macOS está ejecutando la app desde una copia de solo lectura. Muévela a Aplicaciones y ábrela desde ahí.",
        "one is the folder or the address of the other": "una es la carpeta o la dirección de la otra",
        "they are on the same domain": "son del mismo dominio",
        "they turn up together again and again": "aparecen juntas una y otra vez",
        "worked on together": "se trabajó junto a",
        "works on": "trabaja en",
        "you copied something from there": "copiaste algo de ahí",
        "# Your brain\n\nThis is an ordinary folder of ordinary Markdown files. No proprietary database, no secret\nformat, no server. If you walk away from BeLauncher tomorrow you take this folder with you\nand lose nothing. That is the only honest way to ask you to put your company's memory in\nhere.\n\n## What is in each folder\n\n| Folder | What for |\n| --- | --- |\n| `objects` | What the company believes today: decisions, policies, commitments, notes. |\n| `commits` | How each thing got there: who proposed it, who confirmed it, when. |\n| `attachments` | What backs a memory up: a PDF, a screenshot, a contract. |\n| `people` | Clients, partners, the team. |\n| `projects` | What you are working on. |\n| `meetings` | Raw notes, before they are distilled. |\n| `inbox` | Whatever arrives with nowhere to go. Emptying it is the job. |\n\n## How it fills up\n\nNot by hand. From the launcher:\n\n- **`remember that …`** proposes a memory. Note \"proposes\": nothing gets in here without\n          you confirming it. A brain that writes itself is a brain you cannot trust.\n        - **`capture meeting`** with your notes on the clipboard pulls out the decisions and the\n          commitments and offers them to you one at a time.\n        - **`what did we decide about …`** gives you back what still stands today, not everything\n          that was ever said.\n        - **`pulse`** tells you what is going stale: contradictions, overdue commitments, decisions\n          nobody has looked at in six months.\n\n        ## How to attach something\n\n        Copy the file into `attachments/` and name it with the id of the memory it belongs to, or\n        drag it onto the memory from the launcher. In the Markdown it ends up as an ordinary\n        relative link, so any editor opens it.\n\n        ## It is just a folder\n\n        Every file in here is plain `.md`. Any Markdown editor opens it, and if you want history and\n        backups you can make this folder a git repository yourself — nothing in the app depends on\n        it either way.\n\n        Mind the obvious one: if you push this to a repository, whatever is in here ends up wherever\n        that repository is. For company memory, make it private.":
            "# Tu cerebro\n\nEsto es una carpeta normal con archivos Markdown normales. No hay base de datos\npropietaria, ni formato secreto, ni servidor. Si mañana dejas BeLauncher, te llevas esta\ncarpeta y no pierdes nada. Esa es la única forma honesta de pedirte que metas aquí la\nmemoria de tu empresa.\n\n## Qué hay en cada carpeta\n\n| Carpeta | Para qué |\n| --- | --- |\n| `objects` | Lo que la empresa cree hoy: decisiones, políticas, compromisos, notas. |\n| `commits` | Cómo llegó ahí cada cosa: quién la propuso, quién la confirmó, cuándo. |\n| `attachments` | Lo que respalda una memoria: un PDF, una captura, un contrato. |\n| `people` | Clientes, socios, el equipo. |\n| `projects` | En qué estás trabajando. |\n| `meetings` | Notas en crudo, antes de destilarlas. |\n| `inbox` | Lo que llega sin sitio. Vaciarlo es la tarea. |\n\n## Cómo se llena\n\nNo a mano. Desde el lanzador:\n\n- **`recordar que …`** propone una memoria. Fíjate en «propone»: nada entra aquí sin que\n  tú lo confirmes. Un cerebro que se escribe solo es un cerebro en el que no puedes\n  confiar.\n- **`capturar reunion`** con tus notas copiadas saca las decisiones y los compromisos y\n  te los propone uno a uno.\n- **`qué decidimos sobre …`** te devuelve lo que está vigente hoy, no todo lo que se dijo\n  alguna vez.\n- **`pulse`** te dice qué se está pudriendo: contradicciones, compromisos vencidos,\n  decisiones que nadie ha revisado en medio año.\n\n## Cómo adjuntar algo\n\nCopia el archivo dentro de `attachments/` y nómbralo con el id de la memoria a la que\npertenece, o arrástralo sobre la memoria desde el lanzador. En el Markdown queda como un\nenlace relativo normal, así que Obsidian, GitHub y cualquier editor lo abren.\n\n## Es solo una carpeta\n\nTodo lo que hay aquí son archivos `.md` normales. Cualquier editor de Markdown los abre, y\nsi quieres historial y copia de seguridad puedes convertir esta carpeta en un repositorio\ngit tú mismo: la app no depende de eso ni en un caso ni en el otro.\n\nOjo con lo obvio: si subes esto a un repositorio, lo que haya aquí dentro estará donde esté\nese repositorio. Para memoria de empresa, privado.",
        ". Nothing is being kept.": ". No se está guardando nada.",
        "A design": "Un diseño",
        "A link": "Un enlace",
        "A table": "Una tabla",
        "An email": "Un correo",
        "An error": "Un error",
        "An invoice": "Una factura",
        "Awake · finishing": "Sin dormir · terminando",
        "Awake · no end": "Sin dormir · indefinido",
        "Calculation": "Cálculo",
        "Capturing what you do.": "Capturando lo que haces.",
        "Code": "Código",
        "Deleted for good: ": "Se borra para siempre: ",
        "Images": "Imágenes",
        "It is still going on; it gets indexed when it ends.": "Todavía está pasando; se indexa al terminar.",
        "Nothing was kept during that stretch.": "En ese rato no hay nada guardado.",
        "Paused for a while": "En pausa un rato",
        "Result": "Resultado",
        "The package is damaged, or it is not from BeLauncher.": "El paquete está dañado o no es de BeLauncher.",
        "The team key does not open this package.": "La clave del equipo no abre este paquete.",
        "Try again in a moment.": "Intenta de nuevo en un momento.",
        "Until I turn it off": "Hasta que lo apague",
        "We could not connect. Check your connection and try again.": "No pudimos conectar. Revisa tu conexión e intenta otra vez.",
        "When it closes": "Al cerrarla",
        "When it offers a memory": "Al proponer una memoria",
        "When the window opens": "Al abrir la ventana",
        "When you copy": "Al copiar",
        "You already have a /%@ command. Rename one of the two.": "Ya tienes un comando /%@. Cambia el nombre de uno de los dos.",
        "by meaning": "por significado",
        "by words": "por palabras",
        "conversation": "conversación",
        "from:": "de:",
        "matches on everything": "coincide en todo",
        "system": "del sistema",
        "the open file": "el archivo abierto",
        "·empty·": "·vacía·",
        "Copy": "Copiar",
        "Danger": "Peligro",
        "Manage": "Gestionar",
        "With AI": "Con IA",
        "%1$@%% of %2$@": "%1$@%% de %2$@",
        "%@ can consult your brain now. Restart it so it notices.": "%@ ya puede consultar tu cerebro. Reinícialo para que lo vea.",
        "%@ from the clipboard": "%@ del portapapeles",
        "%@ from the graph": "%@ del grafo",
        "%@ holds your whole session up. Closing it logs you out.": "%@ sostiene tu sesión entera. Cerrarlo te desconecta.",
        "%@'s configuration could not be written.": "No se pudo escribir la configuración de %@.",
        "Are “%1$@” and “%2$@” the same thing? I ask because %3$@.": "¿«%1$@» y «%2$@» son lo mismo? Lo pregunto porque %3$@.",
        "Awake · %1$@ h %2$@ min": "Sin dormir · %1$@ h %2$@ min",
        "Awake · %@ min": "Sin dormir · %@ min",
        "Keep the Mac awake · %@": "No dejar dormir el Mac · %@",
        "Paused. It comes back on its own in %@ min.": "En pausa. Vuelve solo en %@ min.",
        "Place “%@”": "Colocar «%@»",
        "Save this window layout as “%@”": "Guardar este reparto de ventanas como «%@»",
        "The %@ key is missing. Save it in Settings; it stays in your Keychain.": "Falta la clave de %@. Guárdala en Ajustes; se queda en tu Llavero.",
        "The model could not be reached: %@": "No se pudo hablar con el modelo: %@",
        "The provider answered HTTP %@.": "El proveedor respondió HTTP %@.",
        "This package was written by a newer version (format %@).": "Este paquete lo escribió una versión más nueva (formato %@).",
        "Your role (%@) does not allow that.": "Tu rol (%@) no permite hacer eso.",
        "entry with no name": "entrada sin nombre",
        "it turns up next to %@ other things": "aparece junto a %@ cosas más",
        "they are spelled the same but for case, accents or hyphens": "se escriben igual salvo mayúsculas, acentos o guiones",
        "you came back on %@ different days": "volviste %@ días distintos",
        "The download is not signed by Believe (found: %@). ": "La descarga no está firmada por Believe (encontrado: %@). ",
        "no signature": "sin firma",
        "you stayed %@ minutes": "estuviste %@ minutos",
        "%@ passage(s)": "%@ pasaje(s)",
        "from %1$@ to %2$@": "de %1$@ a %2$@",
        "seen %@ time(s)": "visto %@ vez(es)",
        "Accessibility permission is missing. System Settings › Privacy & Security › Accessibility.": "Falta el permiso de Accesibilidad. Ajustes del sistema › Privacidad y seguridad › Accesibilidad, y activa BeLauncher.",
        "BeLauncher: keep the Mac awake": "BeLauncher: no dejar dormir el Mac",
        "Capture is paused": "La captura está en pausa",
        "Close": "Cerrar",
        "Copy it all": "Copiar todo",
        "Fill it all in": "Rellenar todo",
        "Five things and you know how to use it": "Cinco cosas y ya sabes usarlo",
        "Force quit": "Forzar la salida",
        "Free up some space and try again.": "Libera espacio y vuelve a intentarlo.",
        "Get the brain ready": "Poner a punto el cerebro",
        "Go back": "Volver atrás",
        "Hide the detail": "Ocultar el detalle",
        "I could not check the free space on disk.": "No pude comprobar el espacio libre en disco.",
        "I could not find the display.": "No encontré la pantalla.",
        "I could not read the window.": "No pude leer la ventana.",
        "I found no window to save. Are they all minimised?": "No encontré ninguna ventana que guardar. ¿Están todas minimizadas?",
        "I installed it already, look again": "Ya lo instalé, vuelve a mirar",
        "I need Accessibility permission to move other apps' windows.": "Necesito permiso de Accesibilidad para mover ventanas de otras apps.",
        "I need Accessibility permission to move windows.": "Necesito permiso de Accesibilidad para mover ventanas.",
        "I need Accessibility permission to see where the windows are.": "Necesito permiso de Accesibilidad para ver dónde están las ventanas.",
        "It changes something outside BeLauncher": "Cambia algo fuera de BeLauncher",
        "It copied the result to the clipboard": "Copió el resultado al portapapeles",
        "It has turned up once. That barely weighs anything.": "Ha aparecido una vez. Con eso apenas pesa.",
        "It usually happens with system windows and dialogs.": "Suele pasar con ventanas de sistema y diálogos.",
        "It will not be able to save anything. Whatever is unsaved is lost.": "No podrá guardar nada. Lo que tenga sin guardar se pierde.",
        "Look at what is on this Mac": "Mirar qué hay en este Mac",
        "Looking at what is on this Mac…": "Mirando qué hay en este Mac…",
        "Mark removed.": "Quitada la marca.",
        "Marked. From now on it weighs the most in searches.": "Marcado. A partir de ahora pesa lo máximo en las búsquedas.",
        "No brief": "Sin encargo",
        "No corpus folder is set up yet.": "No hay carpeta de corpus configurada todavía.",
        "Noted: not the same thing. I will not offer it again.": "Anotado: no son lo mismo. No vuelvo a proponerlo.",
        "Nothing could be made out in that audio.": "No se entendió nada en ese audio.",
        "Nothing under way.": "Nada en marcha.",
        "Pick two entities to be able to join them.": "Elige dos entidades para poder unirlas.",
        "Placing windows is the one thing macOS will not let anything do without this permission.": "Colocar ventanas es lo único que macOS no deja hacer sin este permiso.",
        "Purchase email": "Correo de compra",
        "Put back what was on the clipboard": "Recuperar lo que había en el portapapeles",
        "Raise the relevance bar and whatever barely weighs anything goes.": "Sube el listón de relevancia y se va lo que apenas pesa.",
        "Ready. Edit whatever you want and run it when it is.": "Listo. Edita lo que quieras y ejecútalo cuando esté.",
        "Run the steps": "Ejecutar los pasos",
        "Search actions…": "Buscar acciones…",
        "See what would be deleted": "Ver qué se borraría",
        "Sites it never looks at": "Webs que nunca mira",
        "Take it off the list. It gets looked at again from that moment on.": "Quitar de la lista. Vuelve a mirarla desde ese momento.",
        "That app does not tell macOS where its window is, so it cannot be placed.": "Esa app no le cuenta a macOS dónde está su ventana, así que no se puede colocar.",
        "That command no longer exists.": "Ese comando ya no existe.",
        "That process is no longer running.": "Ese proceso ya no está corriendo.",
        "That process no longer exists.": "Ese proceso ya no existe.",
        "That window returned a size that makes no sense.": "Esa ventana devolvió un tamaño que no tiene sentido.",
        "The Mac will not sleep until you turn this off from the menu bar.": "El Mac no se dormirá hasta que lo apagues desde la barra de menús.",
        "The app did not answer in time. If it has just opened or is busy, try again.": "La app no respondió a tiempo. Si acaba de abrirse o está ocupada, prueba otra vez.",
        "The brain fills itself while you work, if you turned capture on. Try “Everything” up top.": "El cerebro se llena solo mientras trabajas, si activaste la captura. Prueba con «Todo» arriba.",
        "The command could not be completed.": "El comando no se pudo completar.",
        "The keys": "Las teclas",
        "There is no speech model for your language on this Mac.": "No hay un modelo de voz para tu idioma en este Mac.",
        "There is no window in front. Open an app, summon BeLauncher over it and try again.": "No hay ninguna ventana delante. Abre una app, súmmona BeLauncher encima y vuelve a intentarlo.",
        "There is nothing to draw here yet.": "Todavía no hay nada que dibujar aquí.",
        "There is only one display.": "Solo hay una pantalla.",
        "This canvas has nothing to run: it is all text for you to use.": "Este lienzo no tiene nada que ejecutar: es todo texto para que lo uses tú.",
        "Time is a first-class axis: this is a graph of things that happened.": "El tiempo es un eje de primera: esto es un grafo de cosas que pasaron.",
        "Try fewer words, or widen the period.": "Prueba con menos palabras o amplía el periodo.",
        "Type “/” in the launcher to see what can be commissioned.": "Escribe «/» en el lanzador para ver lo que se puede encargar.",
        "What the brain knows about you": "Lo que el cerebro sabe de ti",
        "Yes, they are the same": "Sí, son lo mismo",
        "You already told me they are not the same. I will not ask again.": "Ya me dijiste que no son lo mismo. No vuelvo a preguntarlo.",
        "You marked it as important yourself.": "Lo marcaste tú como importante.",
        "edited by you": "editado por ti",
        "factory setting": "de fábrica",
        "macOS blocked this. Allow BeLauncher in Settings › Privacy › Automation.": "macOS bloqueó esta acción. Autoriza BeLauncher en Ajustes › Privacidad › Automatización.",
        "macOS would not let me turn the awake mode on.": "macOS no dejó activar el modo despierto.",
        "no cost": "sin coste",
        "that client keeps no command at all": "ese cliente no guarda ningún comando",
        "Force “%@” to quit?": "¿Forzar la salida de «%@»?",
        "Homebrew could not be run: %@": "No se pudo ejecutar Homebrew: %@",
        "Homebrew could not install Ollama (code %@). Try from ollama.com.": "Homebrew no pudo instalar Ollama (código %@). Prueba desde ollama.com.",
        "It could not be run: %@": "No se pudo ejecutar: %@",
        "That app": "Esa app",
        "The Mac will not sleep for %@.": "El Mac no se dormirá durante %@.",
        "The note could not be saved: %@": "No se pudo guardar la nota: %@",
        "The notes folder could not be opened: %@": "No se pudo abrir la carpeta de notas: %@",
        "We could not save the licence to the Keychain: %@": "No pudimos guardar la licencia en el Llavero: %@",
        "macOS does not have %@ where it was expected.": "macOS no tiene %@ donde se esperaba.",
        "macOS would not let me close “%@”.": "macOS no dejó cerrar «%@».",
        "since %@": "desde %@",
        "“%1$@” failed: %2$@": "«%1$@» falló: %2$@",
        "“%@” copied.": "«%@» copiado.",
        "“%@” could not be closed (does it belong to another user?).": "No se pudo cerrar «%@» (¿es de otro usuario?).",
        "“%@” is in full screen, and macOS will not let those windows move. Take it out of full screen and try again.": "«%@» está en pantalla completa y macOS no deja mover esas ventanas. Sácala de pantalla completa y vuelve a intentarlo.",
        "“%@” would not close. Try ⌘K → Force quit.": "«%@» no quiso cerrarse. Prueba con ⌘K → Forzar la salida.",
        "On-device transcription needs macOS 26 or later. This version of macOS has no speech model that works without sending the audio off the Mac, so it stays off.": "La transcripción en local necesita macOS 26 o posterior. En esta versión de macOS no hay un modelo de voz que funcione sin enviar el audio fuera del Mac, así que no se activa.",
        "The speech model is half installed and returns invented text, so nothing is kept. Download the language from Settings to fix it.": "El modelo de voz está instalado a medias y devuelve texto inventado, así que no se guarda nada. Descarga el idioma desde Ajustes para arreglarlo.",
        "Open privacy…": "Abrir privacidad…",
        "The window changed while I was looking at it. Try again.": "La ventana cambió mientras la miraba. Vuelve a intentarlo.",
        " and %@ more": " y %@ más",
        "## Can be undone": "## Se puede deshacer",
        "## What it did": "## Qué hizo",
        "## Where it came from": "## De dónde salió",
        "%@ cannot be written to. Move BeLauncher to Applications and try again.": "No se puede escribir en %@. Mueve BeLauncher a Aplicaciones y vuelve a intentarlo.",
        "%@ less relevant nodes are missing. Narrow the dates or raise the bar.": "Faltan %@ nodos menos relevantes. Acota por fecha o sube el listón.",
        "%@ was already connected.": "%@ ya estaba conectado.",
        "A memory needs a sentence describing it.": "Una memoria necesita una frase que la describa.",
        "Activate": "Activar",
        "Before “%@” you were on this": "Antes de «%@» estabas en esto",
        "Browser history": "Historial del navegador",
        "By relation": "Por relación",
        "By time": "Por tiempo",
        "Campaign": "Campaña",
        "Client onboarding": "Alta de cliente",
        "Close my day": "Cierra mi día",
        "Close the app": "Cerrar la app",
        "Connect": "Conectar",
        "Continue": "Continuar",
        "Conversations with the AI": "Conversaciones con la IA",
        "Copied from ": "Copiado de ",
        "Copied from %@": "Copiado de %@",
        "Copy the answer": "Copiar la respuesta",
        "Copy the passage": "Copiar el pasaje",
        "Copy the path": "Copiar ruta",
        "Copy the sentence": "Copiar la frase",
        "Copy this block": "Copiar este bloque",
        "Delete from the history": "Borrar del historial",
        "Describe what is there": "Descríbeme lo que se ve",
        "Draft the reply": "Redáctame la respuesta",
        "Empty. Fill it in or write it yourself.": "Vacío. Rellénalo o escríbelo tú.",
        "Explain this error": "Explícame este error",
        "Explain what it does": "Explícame qué hace",
        "Explain what it says": "Explícame qué dice",
        "Export my commands": "Exportar mis comandos",
        "Export…": "Exportar…",
        "Extract the text": "Extrae los textos",
        "File it where it belongs": "Archívala donde toca",
        "Files that back a memory up: a PDF, a screenshot, a contract.": "Archivos que respaldan una memoria: un PDF, una captura, un contrato.",
        "Films": "Películas",
        "Find what stands out": "Busca lo que se sale de la norma",
        "Follow up on a proposal": "Haz seguimiento de una propuesta",
        "Force quit (loses what is unsaved)": "Forzar la salida (pierde lo no guardado)",
        "Get me ready for any meeting": "Prepárame para cualquier reunión",
        "Give it an alias": "Asignar un alias",
        "HTTP %@ while downloading": "HTTP %@ al descargar",
        "I could not work out the vectors: %@": "No pude calcular los vectores: %@",
        "I do not know “%@”": "No conozco a «%@»",
        "Import commands…": "Importar comandos…",
        "Import shared commands.": "Importar comandos compartidos.",
        "Import…": "Importar…",
        "Installing…": "Instalando…",
        "It all stays on this Mac.": "Todo se queda en este Mac.",
        "It gathered context from %@ source(s)": "Reunió contexto de %@ fuente(s)",
        "Keep as a memory": "Guardar como memoria",
        "Keep it as a memory": "Guardarlo como memoria",
        "Keep it in the brain": "Guárdalo en el cerebro",
        "Keeping what it learned": "Guardando lo aprendido",
        "Look into it": "Investígalo",
        "Look it up on the web": "Búscalo en la web",
        "Meeting prep": "Preparación de reunión",
        "Move to the trash": "Mover a la papelera",
        "Music": "Música",
        "Next step": "Siguiente paso",
        "No title": "Sin título",
        "Nothing was left half done before “%@”": "No quedó nada a medias antes de «%@»",
        "Offer me commands when I repeat something": "Proponerme comandos cuando repito algo",
        "Onboard a new client": "Alta de un cliente nuevo",
        "Open with…": "Abrir con…",
        "Paste into the previous app": "Pegar en la app anterior",
        "Place the window": "Colocar la ventana",
        "Project wrap-up": "Cierre de proyecto",
        "Pull out what they are asking for": "Saca lo que me piden",
        "Pull the tasks out of this": "Saca las tareas de esto",
        "Put a campaign together": "Monta una campaña",
        "Quick look": "Vista rápida",
        "Raw notes before they are distilled into decisions.": "Notas en crudo antes de destilarlas en decisiones.",
        "Root of the disk": "Raíz del disco",
        "Save as a snippet": "Guardar como snippet",
        "Search YouTube": "Buscar en YouTube",
        "See the plan": "Ver el plan",
        "See what it did": "Ver qué hizo",
        "Select some text first.": "Selecciona un texto primero.",
        "Selected in another app": "Seleccionado en otra app",
        "Share…": "Compartir…",
        "Sum it up": "Resúmelo",
        "Tell me how to fix it": "Dime cómo se arregla",
        "Tell me what is wrong": "Dime qué está mal",
        "That commit has already been decided.": "Ese commit ya se decidió.",
        "The %@ key is missing, so the vectors cannot be worked out.": "Falta la clave de %@ para calcular los vectores.",
        "The application could not be replaced: %@": "No se pudo reemplazar la aplicación: %@",
        "The embedding model returned nothing.": "El modelo de embeddings no devolvió nada.",
        "The end date cannot come before the start date.": "La fecha de fin no puede ser anterior a la de inicio.",
        "The history of how each thing got there: who proposed it and who confirmed it.": "El historial de cómo llegó ahí cada cosa: quién la propuso y quién la confirmó.",
        "The model returned %1$@ vectors for %2$@ passages.": "El modelo devolvió %1$@ vectores para %2$@ pasajes.",
        "There is no commit %@.": "No existe el commit %@.",
        "There is no saved layout by that name.": "No hay ningún reparto guardado con ese nombre.",
        "There is no “%1$@” inside %2$@.": "No existe «%1$@» dentro de %2$@.",
        "This licence is already on %@ Macs. Release one to activate this one.": "Esta licencia ya está en %@ Macs. Libera uno para activar este.",
        "Translate it": "Tradúcelo",
        "Turn a call into actions": "Convierte una llamada en acciones",
        "Turn it into Markdown": "Pásala a Markdown",
        "Type “%@” to find it.": "Escribe «%@» para encontrarlo.",
        "Type “%@” to run it.": "Escribe «%@» para ejecutarlo.",
        "Updates": "Actualizaciones",
        "What the brain concluded from your days, every sentence with its citation.": "Lo que el cerebro concluyó de tus días, cada frase con su cita.",
        "What the company believes: decisions, policies, commitments, notes. One file per thing.": "Lo que la empresa cree: decisiones, políticas, compromisos, notas. Un archivo por cosa.",
        "What you are working on.": "En qué estáis trabajando.",
        "What you did, in stretches: one file per episode of work.": "Lo que hiciste, por tramos: un archivo por episodio de trabajo.",
        "Whatever arrives with nowhere to go yet. Emptying it is the job, not filling it.": "Lo que llega sin sitio todavía. Vaciarlo es la tarea, no llenarlo.",
        "When something fails": "Cuando algo falla",
        "Who and what: people, projects, companies and subjects, with every name they answer to.": "Quién y qué: personas, proyectos, empresas y asuntos, con todos sus nombres.",
        "Who is who: clients, partners, the team.": "Quién es quién: clientes, socios, el equipo.",
        "Wrong email or key.": "Correo o clave incorrectos.",
        "no detail": "sin detalle",
        "no title": "sin titulo",
        "remember that…": "recordar que…",
        "“%@”": "«%@»",
        "“%@” is a separate thing again.": "«%@» vuelve a ser algo aparte.",
        "“%@” is out of the brain.": "«%@» fuera del cerebro.",
        "↩ copy": "↩ copiar",
        "≈%@ tokens from your provider.": "≈%@ tokens de tu proveedor.",
        " BeLauncher is now at %@.": " BeLauncher está ahora en %@.",
        " These are not open: %@.": " No están abiertas: %@.",
        " · also ": " · también ",
        "%@ is a system service. Closing it leaves the Mac in an odd state until you restart.": "%@ es un servicio del sistema. Cerrarlo deja el Mac en un estado raro hasta que reinicies.",
        "%@ is part of the desktop. If you really want to restart it, do it from macOS's Force Quit, which reopens it on its own.": "%@ es parte del escritorio. Si de verdad quieres reiniciarlo, hazlo desde Forzar salida de macOS, que lo vuelve a abrir solo.",
        "%@ window(s) placed.": "Colocadas %@ ventana(s).",
        "%@'s configuration file has something in it that is not valid JSON. Open it and fix it, or delete it and try again: I will not overwrite it, because there may be other connections of yours in there.": "El archivo de configuración de %@ tiene algo que no es JSON válido. Ábrelo y arréglalo, o bórralo y vuelve a intentarlo: no lo voy a sobrescribir, porque ahí puede haber otras conexiones tuyas.",
        "Complete the keyword": "Completar palabra clave",
        "Copy it expanded": "Copiar expandido",
        "Copy the link": "Copiar enlace",
        "Copy the name": "Copiar nombre",
        "Copy the result": "Copiar resultado",
        "Delete the flow": "Borrar flujo",
        "Delete the snippet": "Borrar snippet",
        "Delete the workflow": "Borrar workflow",
        "Edit in Settings": "Editar en Ajustes",
        "Edit the steps": "Editar pasos",
        "I cannot read %@'s history. macOS protects it: give BeLauncher Full Disk Access in System Settings, Privacy & Security.": "No puedo leer el historial de %@. macOS lo protege: concede Acceso total al disco a BeLauncher en Ajustes del Sistema, Privacidad y seguridad.",
        "I could not read %1$@'s history: %2$@": "No pude leer el historial de %1$@: %2$@",
        "Open the link": "Abrir enlace",
        "Search Google": "Buscar en Google",
        "See it in Activity Monitor": "Verlo en Monitor de Actividad",
        "The licence server refused the request (HTTP %@). It is not your key: write to us if it keeps happening.": "El servidor de licencias rechazó la petición (HTTP %@). No es tu clave: escríbenos si sigue pasando.",
        "There are already %@ missions under way. Wait for them to finish or cancel one.": "Ya hay %@ misiones en marcha. Espera a que acaben o cancela una.",
        "There is no model available right now. If you use Ollama or LM Studio, open it and try again; if you would rather use one in the cloud, put your key in Settings › Intelligence.": "No hay ningún modelo disponible ahora mismo. Si usas Ollama o LM Studio, ábrelo y vuelve a intentarlo; si prefieres uno en la nube, pon tu clave en Ajustes › Inteligencia.",
        "This content is marked confidential and %@ is not local. Change it in Settings or use a model on your Mac.": "Este contenido está marcado como confidencial y %@ no es local. Cámbialo en Ajustes o usa un modelo en tu Mac.",
        "You have done this %1$@ times: %2$@. Shall I turn it into a command?": "Has hecho esto %1$@ veces: %2$@. ¿Lo convierto en un comando?",
        "\n\nComes from: ": "\n\nSale de: ",
        "another result": "otro resultado",
        "brain.html is missing from the bundle.": "Falta brain.html en el paquete.",
        "macOS would not let the window be read (error %@). Run “BeLauncher --diagnose-windows” and send us what comes out.": "macOS no dejó leer la ventana (error %@). Ejecuta «BeLauncher --diagnose-windows» y mándanos lo que salga.",
        "open": "abrir",
        "related to %@": "relacionado con %@",
        "the path kept in that client, %1$@, no longer leads to anything runnable.%2$@": "la ruta guardada en ese cliente, %1$@, ya no lleva a nada ejecutable.%2$@",
        "“%@” does not tell macOS where its windows are. Run “BeLauncher --diagnose-windows” with it in front and send us what comes out.": "%@ no le cuenta a macOS dónde están sus ventanas. Ejecuta «BeLauncher --diagnose-windows» con ella delante y mándanos lo que salga.",
        "“%@” will not let its windows move. ": "«%@» no deja que se muevan sus ventanas. ",
        "## Permissions used": "## Permisos usados",
        "File": "Archivo",
        "Folder": "Carpeta",
        "Home folder": "Carpeta personal",
        "It needs a permission: %@": "Necesita permiso: %@",
        "Meetings and clipboard": "Reuniones y portapapeles",
        "Missions": "Misiones",
        "Note saved": "Nota guardada",
        "Permissions": "Permisos",
        "Proposal": "Propuesta",
        "Proposal saved": "Propuesta guardada",
        "Proposal · confirm or discard": "Propuesta · confirma o descarta",
        "Window": "Ventana",
        "Windows": "Ventanas",
        "Work": "Trabajo",
        "new folder": "nueva carpeta",
        "unknown": "desconocido",
        "## Cost": "## Coste",
        "## Result": "## Resultado",
        "Answer": "Respuesta",
        "Command": "Comando",
        "Flow": "Flujo",
        "Link": "Enlace",
        "Process": "Proceso",
        "Recollection": "Recuerdo",
        "Shortcut": "Atajo",
        "System": "Sistema",
        "Company": "Empresa",
        "Episode": "Episodio",
        "Person": "Persona",
        "Project": "Proyecto",
        "Subject": "Asunto",
        "Thing": "Cosa",
        " · %@ person(s)": " · %@ persona(s)",
        "%1$@ nodes · %2$@ relations": "%1$@ nodos · %2$@ relaciones",
        "Episode · ": "Episodio · ",
        "Model": "Modelo",
        "Compact": "Compactar",
        "Compacted: %@ freed.": "Compactada: %@ liberados.",
        "Compacting…": "Compactando…",
        "It could not be compacted: %@": "No se pudo compactar: %@",
        "It is taking far more room than its contents need. Compacting rewrites it and gives the space back; it needs enough free disk for one copy of the result.": "Está ocupando mucho más de lo que necesita su contenido. Compactar la reescribe y devuelve el espacio; hace falta disco libre para una copia del resultado.",
        "There is not enough free disk. It needs about %@ for the new copy.": "No hay disco libre suficiente. Hacen falta unos %@ para la copia nueva.",
        "Test preferred model": "Probar el modelo preferido",
        "Test": "Probar",
        "The partial download is saved. Retry resumes it instead of starting over.": "La descarga parcial se guardó. Reintentar la continúa en vez de empezar de cero.",
        "Not installed. Download sets up its private runtime inside BeLauncher; no system Python is needed.": "No instalado. La descarga prepara su runtime privado dentro de BeLauncher; no hace falta Python del sistema.",
        "Model not installed. Apple's on-device speech engine remains available on this Mac.": "Modelo no instalado. El motor de voz local de Apple sigue disponible en este Mac.",
        "Model not installed. Qwen is required for local transcription on this version of macOS.": "Modelo no instalado. Qwen es necesario para transcribir localmente en esta versión de macOS.",
        "verify the voice engine": "verificar el motor de voz",
        "The capture service is not available.": "El servicio de captura no está disponible.",
        "%@ is not ready. Start the local server or save and verify its key.": "%@ no está listo. Inicia el servidor local o guarda y verifica su clave.",
        "Testing %@…": "Probando %@…",
        "%@ connected: %@": "%@ conectado: %@",
        "Ready to answer with %@": "Listo para responder con %@",
        "Connection found. Run Test to verify a real answer.": "Conexión encontrada. Pulsa Probar para verificar una respuesta real.",
        "Save a key and verify the connection": "Guarda una clave y verifica la conexión",
        "No key saved": "No hay clave guardada",
        "Not verified yet": "Aún no se ha verificado",
        "Read completed · %@ new passages": "Lectura terminada · %@ pasajes nuevos",
        "Capture is paused. Nothing was read.": "La captura está pausada. No se leyó nada.",
        "Capture was deferred: %@": "La captura se aplazó: %@",
        "Another source is already being read.": "Ya se está leyendo otra fuente.",
        "Read failed: %@": "La lectura falló: %@",
        "Granted": "Concedido",
        "Full Disk Access granted": "Acceso total al disco concedido",
        "Keep my Brain up to date": "Mantener mi Brain actualizado",
        "Read only the enabled local sources and keep links to their originals.": "Lee solo las fuentes locales activadas y conserva enlaces a sus originales.",
        "Sync all": "Sincronizar todo",
        "The stream stopped after %@ characters: %@": "El flujo se detuvo después de %@ caracteres: %@",
        "Local Mail, Messages and Notes": "Mail, Mensajes y Notas locales",
        "Let your Brain connect relevant evidence from Apple Mail, Messages and Notes to the original item on this Mac.": "Permite que tu Brain conecte evidencia relevante de Mail, Mensajes y Notas con el elemento original de este Mac.",
        "Their protected local databases. BeLauncher reads them on this Mac, keeps only relevant text plus a link to the original, and never uploads them.": "Sus bases locales protegidas. BeLauncher las lee en este Mac, conserva solo texto relevante y un enlace al original, y nunca las sube.",
        "Apps, files, clipboard, manual notes and every launcher command still work. These three sources remain disconnected.": "Las apps, archivos, portapapeles, notas manuales y comandos del launcher siguen funcionando. Estas tres fuentes quedan desconectadas.",
        "I could not read every Apple Mail message. Check Full Disk Access and the Mail store.": "No pude leer todos los mensajes de Apple Mail. Revisa el Acceso total al disco y el almacén de Mail.",
        "Apple Messages could not finish reading its local database.": "Apple Mensajes no pudo terminar de leer su base de datos local.",
        "Apple Notes could not finish reading its local database.": "Apple Notas no pudo terminar de leer su base de datos local.",
        "Reminder": "Recordatorio",
        "Reminders": "Recordatorios",
        "Pending reminders and due dates after permission.": "Recordatorios pendientes y fechas de vencimiento después de conceder permiso.",
        "No due date": "Sin fecha de vencimiento",
        "Untitled": "Sin título",
        "Copy the reminder": "Copiar el recordatorio",
        "List and due date": "Lista y fecha de vencimiento",
        "Reminders on this Mac": "Recordatorios de este Mac",
        "Contacts": "Contactos",
        "Contact": "Contacto",
        "Names and contact details after permission.": "Nombres y datos de contacto después de conceder permiso.",
        "Contact detail": "Dato de contacto",
        "Copy contact": "Copiar contacto",
        "Photos": "Fotos",
        "Local photo metadata after permission.": "Metadatos de fotos locales después de conceder permiso.",
        "Photo library": "Fototeca",
        "Photo": "Foto",
        "Open photo": "Abrir foto",
        "Copy path": "Copiar ruta",
        "Album": "Álbum",
        "Local identifier": "Identificador local",
        "%@ photos available locally": "%@ fotos disponibles localmente",
        "Search pending reminders from the launcher and Brain.": "Busca recordatorios pendientes desde el launcher y el Brain.",
        "Only reminder titles, lists and due dates on this Mac.": "Solo títulos, listas y fechas de vencimiento de recordatorios en este Mac.",
        "Everything else works; reminders stay disconnected.": "Todo lo demás funciona; los recordatorios permanecen desconectados.",
        "Find a person, email or phone number without leaving the launcher.": "Encuentra una persona, correo o teléfono sin salir del launcher.",
        "Names and contact details only when you search.": "Nombres y datos de contacto solo cuando buscas.",
        "Everything else works; contacts stay disconnected.": "Todo lo demás funciona; los contactos permanecen desconectados.",
        "Find local photos and open them in Photos.": "Encuentra fotos locales y ábrelas en Fotos.",
        "Photo metadata only; originals are not copied into the Brain.": "Solo metadatos de fotos; los originales no se copian al Brain.",
        "Everything else works; Photos stays disconnected.": "Todo lo demás funciona; Fotos permanece desconectado.",
        "Sources": "Fuentes",
        "Search local sources": "Buscar fuentes locales",
    ]
}
